# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(is_provider: true,
            username: 'redranchgrill',
            name: 'Red Ranch Grill',
            email: 'redranch@email.com',
            password: 'password',
            password_confirmation: 'password',
            address: '123 Dirt Lane Rd.',
            phone: '416-555-1234',
            description: 'Sed chuck pork chop shoulder laborum, pork loin cupidatat dolor landjaeger eiusmod excepteur. Capicola fatback dolore ball tip excepteur kielbasa. Ground round landjaeger exercitation leberkas, ball tip consectetur tri-tip magna in bresaola anim dolore minim. Ut exercitation spare ribs sirloin ribeye aute brisket ex ut beef ribs proident laboris nostrud. ',
            homepage: 'redranchgrill.com',
            photo: '',
            registration: 'RRG12345')
User.create(is_provider: true,
            username: 'sweetsatisfaction',
            name: 'Sweet Satisfaction',
            email: 'sweets@sweetsatisfaction.com',
            password: 'password',
            password_confirmation: 'password',
            address: '52 Cupcake Ave',
            phone: '1-800-222-7890',
            description: 'Gummi bears croissant brownie dessert powder dessert donut. Oat cake cheesecake I love marzipan lemon drops cake cotton candy. Chupa chups halvah pie. Dessert lemon drops carrot cake sweet roll. Marzipan cotton candy cheesecake gummi bears topping dessert jelly beans cake I love. Bonbon chocolate muffin danish. I love I love biscuit tiramisu powder bonbon cake chupa chups.',
            homepage: 'sweetsatisfaction.com',
            photo: '',
            registration: '#SS6437392')
User.create(is_provider: true,
            username: 'hipstercafe',
            name: 'Hipster Cafe',
            email: 'iknewbeforeyou@hipstercafe.com',
            password: 'password',
            password_confirmation: 'password',
            address: '14567 Soliloquent Way',
            phone: '(416) 666-2468',
            description: 'Pug fanny pack copper mug, neutra four loko wayfarers retro tumeric blue bottle tofu. Photo booth gentrify quinoa seitan cornhole food truck. Lyft taxidermy pok pok, pinterest copper mug air plant humblebrag. Gochujang fap tofu sriracha offal, biodiesel lyft kogi tattooed.',
            homepage: 'hipstercafe.com',
            photo: '',
            registration: 'HC03846')
User.create(is_provider: true,
            username: 'greatgreenbean',
            name: 'The Great Green Bean',
            email: 'greatgreanbean@veggiemail.com',
            password: 'password',
            password_confirmation: 'password',
            address: '885 Sweet Potato St',
            phone: '416-333-1234',
            description: 'Celery quandong swiss chard chicory earthnut pea potato. Salsify taro catsear garlic gram celery bitterleaf wattle seed collard greens nori. Grape wattle seed kombu beetroot horseradish carrot squash brussels sprout chard.',
            homepage: 'greatgreenbean.com',
            photo: '',
            registration: 'GGB09876')
User.create(is_provider: true,
            username: 'exceptionalevents',
            name: 'Exceptional Events',
            email: 'events@exceptionalevents.com',
            password: 'password',
            password_confirmation: 'password',
            address: '6543 Smallmouth Ave',
            phone: '416.444.4321',
            description: 'Stargazer paradise fish yellowfin cutthroat trout Sacramento splittail. Canary rockfish Asian carps sabertooth striped bass Atlantic eel gulf menhaden northern lampfish whalefish barramundi man-of-war fish mud minnow! Quillback deep sea smelt seahorse basslet leaffish ilisha. Bass king of herring buffalofish: Atlantic trout torrent fish mora rockfish zander milkfish pumpkinseed New World rivuline. ',
            homepage: 'exceptionalevents.com',
            photo: '',
            registration: 'EE98327')

User.create(is_provider: false,
            username: 'mainstreetmission',
            name: 'Main Street Mission',
            email: 'info@mainstmission.com',
            password: 'password',
            password_confirmation: 'password',
            address: '1212 Main St',
            phone: '416-789-0987',
            description: 'But now forget all about blinds and whiskers for a moment, and, standing in the Right Whale’s mouth, look around you afresh. Seeing all these colonnades of bone so methodically ranged about, would you not think you were inside of the great Haarlem organ, and gazing upon its thousand pipes?',
            homepage: 'mainstmission.org',
            photo: '',
            registration: '12-12-12-212121')
User.create(is_provider: false,
            username: 'londonharbour',
            name: 'London Harbour',
            email: 'londonharbour@gmail.com',
            password: 'password',
            password_confirmation: 'password',
            address: '345 Yorkshire Lane',
            phone: '416-890-0987',
            description: 'Ah’ll box thi ears amet, michael palin gerritetten mardy bum tha what. Mi michael palin euismod tempor viverra where there’s muck there’s brass amet, feugiat ‘sup wi’ ‘im. Gi’ o’er where there’s muck there’s brass where’s tha bin.',
            homepage: 'lodonharbour.com',
            photo: '',
            registration: '39-09874JKHDB')
User.create(is_provider: false,
            username: 'johnstonhouse',
            name: 'Johnston House',
            email: 'mail@johnstonhouse.org',
            password: 'password',
            password_confirmation: 'password',
            address: '390 Johnston St',
            phone: '416-948-9849',
            description: 'Lorizzle izzle yo sizzle amizzle, that’s the shizzle adipiscing elit. Nullizzle velizzle, hizzle volutpizzle, suscipizzle quis, gravida vizzle, check it out. Pellentesque da bomb tortizzle. Sizzle eros. Gangster izzle dolor dapibus turpis tempizzle away.',
            homepage: 'johnstonhouse.org',
            photo: '',
            registration: '3838KJHGB')
User.create(is_provider: false,
            username: 'redroofrefuge',
            name: 'Red Roof Refuge',
            email: 'redroof@hotmail.com',
            password: 'password',
            password_confirmation: 'password',
            address: '9999 Safety St',
            phone: '416-876-5432',
            description: "Top Cat! The most effectual Top Cat! Who's intellectual close friends get to call him T.C., providing it's with dignity. Top Cat! The indisputable leader of the gang. He's the boss, he's a pip, he's the championship. He's the most tip top, Top Cat. This is my boss, Jonathan Hart, a self-made millionaire, he's quite a guy. This is Mrs H., she's gorgeous, she's one lady who knows how to take care of herself. By the way, my name is Max. I take care of both of them, which ain't easy, 'cause when they met it was MURDER!",
            homepage: 'redroofrefuge.com',
            photo: '',
            registration: 'DKJHN36439')
User.create(is_provider: false,
            username: 'saintserenity',
            name: 'Saint Serenity',
            email: 'mail@saintserenity.com',
            password: 'password',
            password_confirmation: 'password',
            address: '333 Courage St',
            phone: '1-888-SERENIT',
            description: 'Fooky napster treemo exaroom skobee wufoo mikonoclast. Orkut geni shelfari scrybe librivox. Goowy manjam platial revver zlango; voo2do yoono piczo. Loopt oyogi fooky rebtel venyo jyve mecanbe yedda. Klostu oyogi coastr, plaxo renkoo, idio fonpods, plazes!',
            homepage: 'sainserenity.org',
            photo: '',
            registration: '384KHJB')
