# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(is_provider: true,
            username: 'BurgerPriest',
            name: 'Burger Priest',
            email: 'bp@burgers.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '220',
            add_name: 'Adelaide',
            add_type: 'st',
            your_city: 'Toronto',
            postal: 'M5H1K4',
            phone: '416-555-1234',
            description: 'Sed chuck pork chop shoulder laborum, pork loin cupidatat dolor landjaeger eiusmod excepteur. Capicola fatback dolore ball tip excepteur kielbasa. Ground round landjaeger exercitation leberkas, ball tip consectetur tri-tip magna in bresaola anim dolore minim. Ut exercitation spare ribs sirloin ribeye aute brisket ex ut beef ribs proident laboris nostrud. ',
            homepage: 'www.burgerpriest.com',
            photo: '',
            registration: 'BPP4567')
User.create(is_provider: false,
            username: 'DailyBread',
            name: 'Daily Bread Food Bank',
            email: 'dailybreadfoodbank@hotmail.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '191',
            add_name: 'NewToronto',
            add_type: 'St',
            your_city: 'Toronto',
            postal: 'M8V2E7',
            phone: '416-203-0050',
            description: 'Daily Bread Food Bank is a registered charity that is fighting hunger in our communities. A distribution hub, Daily Bread provides food and support to almost 200 food programs across Toronto. Daily Bread also works towards long-term solutions to hunger and runs innovative programs to support people on low incomes.',
            homepage: 'www.dailybread.ca',
            photo: '',
            registration: '11888 1549 RR0001')
User.create(is_provider: false,
            username: 'CovenantHouse',
            name: 'The Covenant House',
            email: 'covenanthouse@CH.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '20',
            add_name: 'Gerrard',
            add_type: 'St',
            your_city: 'Toronto',
            postal: 'M5B2P3',
            phone: '416-598-4898',
            description: 'Covenant House Toronto provides 24/7 crisis care to homeless youth, aged 16 to 24, and has a range of services, including education, counselling, and health care.',
            homepage: 'www.covenanthouse.org',
            photo: '',
            registration: '10699 0195 RR0001')

User.create(is_provider: true,
            username: 'RoyalCanadianYachtClub',
            name: 'The Royal Canadian Yacht Club ',
            email: 'rcyc@hotmail.com',
            password: 'password',
            password_confirmation: 'password',
            add_name: 'StGeorge',
            add_number: '141',
            add_type: 'St',
            your_city:'Toronto',
            postal: 'M5R2L8',
            phone: '416-967-7245',
            description: 'The Royal Canadian Yacht Club is a sailing club with a tradition that dates back to 1852. The Club provides yachting activities for racers and cruisers alike from our Island facilities. Our City Clubhouse at 141 St. George Street provides modern facilities for squash, badminton, aquatics and also features a 4,000 square foot fitness area. Fine dining is available in a formal setting as well as casual eating areas for Members and children of all ages.',
            homepage: 'www.rcyc.ca',
            photo: '',
            registration: 'RCYC 00087233')

User.create(is_provider: true,
            username: 'MetroToronto',
            name: 'Metro Toronto Convention Centre ',
            email: 'MTCC@live.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '222' ,
            add_name: 'Bremner',
            add_type: 'blvd',
            your_city: 'Toronto',
            postal: 'M5V3L9',
            phone: '416-585-8000',
            description: 'The Metro Toronto Convention Centre (MTCC) offers stunning meeting spaces, including ballrooms and exhibit halls, in the heart of downtown Toronto.',
            homepage: 'www.mtccc.com',
            photo: '',
            registration: 'MTCC 0098933')

User.create(is_provider: true,
            username: 'Gretzkys',
            name: ' Wayne Gretzkys ',
            email: 'gretzkysrestaurant@gretzky.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '99',
            add_name: 'BlueJays',
            add_type: 'way',
            your_city: 'Toronto',
            postal: 'M5V9G9',
            phone: '416-348-0099',
            description: 'Casual restaurant & sports bar devoted to hockey great Wayne Gretzky, with a rooftop patio.',
            homepage: 'www.gretzkys.com',
            photo: '',
            registration: 'WGR 090038')

User.create(is_provider: true,
            username: 'Gretzkys',
            name: ' Wayne Gretzkys ',
            email: 'gretzkysrestaurant@gretzky.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '99',
            add_name: 'BlueJays',
            add_type: 'way',
            your_city: 'Toronto',
            postal: 'M5V9G9',
            phone: '416-348-0099',
            description: 'Casual restaurant & sports bar devoted to hockey great Wayne Gretzky, with a rooftop patio.',
            homepage: 'www.gretzkys.com',
            photo: '',
            registration: 'WGR 090038')

User.create(is_provider: true,
            username: 'ElCatrin',
            name: ' El Catrin',
            email: 'elcatrin@elcatrin.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '19',
            add_name: 'Tank House',
            add_type: 'Lane',
            your_city: 'Toronto',
            postal: 'M5A 3C4',
            phone: '416-203-2121',
            description: 'Mexican restaurant dedicated to serving great food.',
            homepage: 'www.elcatrin.com',
            photo: '',
            registration: 'FJR 243809')

User.create(is_provider: true,
            username: 'Archeo',
            name: ' Archeo Restaurant ',
            email: 'archeo@archeo.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '31',
            add_name: 'Trinity',
            add_type: 'Street',
            your_city: 'Toronto',
            postal: 'M5A 3C4',
            phone: '416-815-9898',
            description: 'Italian food made with passion, great customer service and nice patio.',
            homepage: 'www.archeo.com',
            photo: '',
            registration: 'JJK 243809')

User.create(is_provider: true,
            username: 'Clunys',
            name: ' Clunys Restaurant ',
            email: 'clunys@cluny.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '35',
            add_name: 'Tank House',
            add_type: 'Lane',
            your_city: 'Toronto',
            postal: 'M5A 3C4',
            phone: '416-203-2632',
            description: 'Huge modern French bistro with updated classic fare & Gallic feel, from marble bar to tiled floors.',
            homepage: 'www.cluny.com',
            photo: '',
            registration: 'JII 08329')

User.create(is_provider: true,
            username: 'BigPita',
            name: ' Big Pita ',
            email: 'bigpita@bigpita.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '115',
            add_name: 'Front',
            add_type: 'Street East',
            your_city: 'Toronto',
            postal: 'M5A 45S',
            phone: '416-366-7482',
            description: 'Huge modern Shwarma restaurant with passionate workers, creating an amazing experience.',
            homepage: 'www.bigpita.com',
            photo: '',
            registration: 'JII 08329')

User.create(is_provider: true,
            username: 'Paramount',
            name: ' Paramount Restaurant ',
            email: 'paramount@paramount.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '161',
            add_name: 'Bay',
            add_type: 'Stret',
            your_city: 'Toronto',
            postal: 'M5J 2S1',
            phone: '416-551-7515',
            description: 'We flew in renowned international chefs to share the most authentic Lebanese recipes using the freshest and finest ingredients which have been passed down for generations to enjoy.',
            homepage: 'www.paramoutcuisine.com',
            photo: '',
            registration: 'JII 04923')

User.create(is_provider: true,
            username: 'SUBU',
            name: ' SUBU Restaurant ',
            email: 'subu@subu.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '106',
            add_name: 'John',
            add_type: 'East',
            your_city: 'Toronto',
            postal: 'M5H 1X9',
            phone: '416-792-7927',
            description: 'Theres a new and exciting way to eat sushi; a twist on the traditional sliced seaweed wrap that is unique and hip again.',
            homepage: 'www.subu.com',
            photo: '',
            registration: 'IEO 08329')

User.create(is_provider: true,
            username: 'Alo',
            name: ' Alo Restaurant ',
            email: 'alo@alo.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '163',
            add_name: 'Spadina',
            add_type: 'Avenue',
            your_city: 'Toronto',
            postal: 'M5V 2L6',
            phone: '416-260-2222',
            description: 'French tasting menu served in stylish, serene surrounds atop a Victorian building.',
            homepage: 'www.alo.com',
            photo: '',
            registration: 'KKJ 0239')

User.create(is_provider: true,
            username: 'Miku',
            name: ' Miku Restaurant ',
            email: 'miku@miku.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '10',
            add_name: 'Bay',
            add_type: 'Street',
            your_city: 'Toronto',
            postal: 'M5J 2R8',
            phone: '647-347-7347',
            description: 'Flame-seared sushi is the specialty at this Japanese fine-dining destination with soaring ceilings.',
            homepage: 'www.miku.com',
            photo: '',
            registration: 'JKI 2930')

User.create(is_provider: true,
            username: 'Omaw',
            name: ' Omaw Restaurant ',
            email: 'omaw@omaw.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '88',
            add_name: 'Ossington',
            add_type: 'Ave',
            your_city: 'Toronto',
            postal: 'M6J 2Z3',
            phone: '647-477-5450',
            description: 'Cool eatery in a heritage building offering creative takes on Southern classics like fried chicken.',
            homepage: 'www.omaw.com',
            photo: '',
            registration: 'KOP 0293')

User.create(is_provider: true,
            username: 'Imanishi',
            name: ' Imanishi Restaurant ',
            email: 'imanishi@imanishi.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '1330',
            add_name: 'Dundas',
            add_type: 'Street West',
            your_city: 'Toronto',
            postal: 'M6J 1Y1',
            phone: '416-706-4225',
            description: 'Homestyle Japanese dishes served in an exposed-brick space with an easygoing atmosphere.',
            homepage: 'www.imanishi.com',
            photo: '',
            registration: 'LOP 0293')

User.create(is_provider: true,
            username: 'CafeBoulud',
            name: ' Cafe Boulud ',
            email: 'cafeboulud@cafeboulud.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '60',
            add_name: 'Yorkvile',
            add_type: 'Ave',
            your_city: 'Toronto',
            postal: 'M4W 0A4',
            phone: '416-963-6000',
            description: 'Daniel Bouluds retooled French brasserie boasts a vintage feel & dishes like rotisserie chicken.',
            homepage: 'www.cafeboulud.com',
            photo: '',
            registration: 'STE 0293')

User.create(is_provider: true,
            username: 'Bar Raval',
            name: ' Bar Raval ',
            email: 'barraval@.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '88',
            add_name: 'Ossington',
            add_type: 'Ave',
            your_city: 'Toronto',
            postal: 'M6J 2Z3',
            phone: '647-477-5450',
            description: 'Cool eatery in a heritage building offering creative takes on Southern classics like fried chicken.',
            homepage: 'www.barraval.com.com',
            photo: '',
            registration: 'KOP 0293')

User.create(is_provider: true,
            username: 'Chabral',
            name: ' Chabral Restaurant ',
            email: 'chabral@chabral.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '90',
            add_name: 'Yorkville',
            add_type: 'Ave',
            your_city: 'Toronto',
            postal: 'M5R 1B9',
            phone: '647-428-6641',
            description: 'Classic French cuisine & wines served in an upscale, petite venue with floor-to-ceiling windows.',
            homepage: 'www.charbel.com',
            photo: '',
            registration: 'KOI 0193')

User.create(is_provider: true,
            username: 'Figo',
            name: ' Figo Restaurant ',
            email: 'figo@figo.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '295',
            add_name: 'Adelaide',
            add_type: 'Street West',
            your_city: 'Toronto',
            postal: 'M5V 1P7',
            phone: '647-503-4074',
            description: 'Contemporary Italian dishes served in a sleek space with soaring windows & an open kitchen.',
            homepage: 'www.figo.com',
            photo: '',
            registration: 'ALL 0193')

User.create(is_provider: true,
            username: 'Frings',
            name: ' Frings Restaurant ',
            email: 'frings@frings.com',
            password: 'password',
            password_confirmation: 'password',
            add_number: '455',
            add_name: 'King',
            add_type: 'Stret West',
            your_city: 'Toronto',
            postal: 'M5V 1K4',
            phone: '416-979-9696',
            description: 'Hip, dimly lit haunt from celeb chef Susur Lee serving a diverse menu of globally inspired fare.',
            homepage: 'www.frings.com',
            photo: '',
            registration: 'SUB 0293')
